name: flutter_financekit
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/dasbudget/flutter_financekit

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  decimal: ^2.3.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.18.1
  plugin_platform_interface: ^2.0.2
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_financekit
        pluginClass: FlutterFinanceKitPlugin
      ios:
        pluginClass: FlutterFinanceKitPlugin
      web:
        pluginClass: FlutterFinanceKitWeb
        fileName: flutter_financekit_web.dart
