// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.dasbudget.flutter_financeKit

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Values that describe the kinds of data in the finance store. */
enum class DataType(val raw: Int) {
  /** The value that describes financial data, such as account information. */
  FINANCIALDATA(0),
  /** The value that describes orders records, such as purchases. */
  ORDERS(1);

  companion object {
    fun ofRaw(raw: Int): DataType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AuthorizationStatus(val raw: Int) {
  /** A person authorized the app to use FinanceKit services. */
  AUTHORIZED(0),
  /** A person denied the use of FinanceKit services for the app */
  DENIED(1),
  /** A person has not chosen whether the app can use FinanceKit services. */
  NOTDETERMINED(2);

  companion object {
    fun ofRaw(raw: Int): AuthorizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FinanceKitApi {
  fun isDataAvailable(type: DataType): Boolean
  fun authorizationStatus(callback: (Result<AuthorizationStatus>) -> Unit)
  fun requestAuthorization(callback: (Result<AuthorizationStatus>) -> Unit)

  companion object {
    /** The codec used by FinanceKitApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `FinanceKitApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: FinanceKitApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_financekit.FinanceKitApi.isDataAvailable", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DataType.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.isDataAvailable(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_financekit.FinanceKitApi.authorizationStatus", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.authorizationStatus() { result: Result<AuthorizationStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data!!.raw))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_financekit.FinanceKitApi.requestAuthorization", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestAuthorization() { result: Result<AuthorizationStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data!!.raw))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
